.setup:
  parallel:
    matrix:
      - DISTRO: [debian, rockylinux]
        MPI: [mpich, openmpi]
        DEVICE: [cpu]
      - DISTRO: [debian]
        MPI: [mpich, openmpi]
        DEVICE: [gpu]
  tags:
    - public-docker
  image: $CI_REGISTRY/nexgf/libnegf/$DISTRO/$MPI-$DEVICE
  variables:
    BUILD_DIR: build-$DISTRO-$MPI-$DEVICE
    CFLAGS: -Wextra -Wall -pedantic
    CXXFLAGS: -Wextra -Wall -pedantic
    LDFLAGS: -Wl,-z,defs
    MALLOC_CHECK_: 3
    MALLOC_PERTURB_: 1


build:
  extends: .setup
  stage: build
  script:
    - mkdir "$BUILD_DIR"
    - WITH_GPU="$( [ "$DEVICE" = 'gpu' ] && echo ON || echo OFF )"
    - cmake
       -DCMAKE_BUILD_TYPE=Debug
       -DBUILD_SHARED_LIBS:BOOL=ON
       -DCMAKE_RULE_MESSAGES:BOOL=OFF
       -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
       -DWITH_TRANSPORT_GPU="$WITH_GPU"
       -DMPIEXEC_MAX_NUMPROCS=8
       -B "$BUILD_DIR"
       -S .
    - num_cpus="$(getconf _NPROCESSORS_ONLN)"
    - echo "Building on $num_cpus CPU cores"
    - cmake --build "$BUILD_DIR" --parallel "$num_cpus"
  artifacts:
    paths:
      - $BUILD_DIR


test:
  extends: .setup
  stage: test
  script:
    - cd "$BUILD_DIR"
    - ctest -LE long --output-on-failure
